# Budgeting Toolkit Configuration

validDestinationAccounts:
  - "1"
  - "11"
  - "8"
  - "14"

validExpenseAccounts:
  - "8"
  - "11"
  - "14"
  - "1"

excludedDescriptions:
  - PAYROLL

excludedTransactionsCsv: excluded_transactions.csv

excludeDisposableIncome: false

minTransactionAmount: 0

moneyMarketAccount: "27"

expectedMonthlyPaycheck: 10472.04

monthlyBudget: 1840

# Additional savings percentage (added to base 30%)
additionalSavingsPercentage: 12.02

# LLM Configuration for optimal transaction classification
llm:
  # Use Claude Sonnet for better reasoning and accuracy
  model: "claude-3-5-sonnet-latest"
  
  # Increase tokens for more detailed analysis
  maxTokens: 2000
  
  # Lower temperature for more consistent categorization
  temperature: 0.1
  
  # Optimal batch sizes for budget classification
  batchSize: 5
  maxConcurrent: 2
  
  # Conservative retry settings
  retryDelayMs: 1500
  maxRetryDelayMs: 30000
  
  # Rate limiting for Sonnet model
  rateLimit:
    maxTokensPerMinute: 40
    refillInterval: 60000
  
  # Circuit breaker for production reliability
  circuitBreaker:
    failureThreshold: 3
    resetTimeout: 90000
    halfOpenTimeout: 45000

