/**
 * DTO for representing a spending insight/recommendation
 * Generated by rule-based analysis of budget data
 */
export interface BudgetInsight {
    /**
     * Type of insight for categorization and styling
     * - 'warning': Issue that needs attention (overspending, unexpected bills)
     * - 'success': Positive performance (under budget, good control)
     * - 'info': Neutral information (transaction counts, frequency)
     * - 'alert': Critical issue requiring action
     */
    type: 'warning' | 'success' | 'info' | 'alert';

    /**
     * Human-readable insight message
     * Examples:
     * - "Going Out is your biggest issue - 43% over budget"
     * - "You had 48 transactions in Going Out (avg $20.81 each)"
     * - "Groceries looking good - stayed under budget"
     */
    message: string;

    /**
     * Priority for sorting insights (lower number = higher priority)
     * Used to display most important insights first
     */
    priority: number;

    /**
     * Optional reference to the budget this insight relates to
     * Allows filtering or highlighting related budget
     */
    relatedBudget?: string;
}
